
cd() { builtin cd "$@"; ls -lah --color=auto; }

alias ll='ls -lah --color=auto'
alias ls='ls -lah --color=auto'
alias l='ls -lah --color=auto'
alias ba='nano ~/.bash_aliases'
alias gitba='git clone https://github.com/nightmac/bash_aliases.git && cp bash_aliases/.bash_aliases ~/ && rm -rf bash_aliases && source ~/.bash_aliases'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../..'
alias path='echo -e ${PATH//:/\\n}'
alias perfserv='iperf3 -s -D'
alias iperf='iperf3 -i .5 -t 5 -c '
alias yes='yes > /dev/null &'
alias yes4='yes yes yes yes'
alias yess='killall yes'
alias temp='vcgencmd measure_temp'
alias indigo='indigo_server indigo_ccd_qhy indigo_mount_synscan indigo_ccd_asi indigo_focuser_mypro2 -i /usr/bin/indi_servoblaster_cap & sudo servod'
alias indigoagents='indigo_server indigo_agent_imager indigo_agent_mount indigo_agent_guide indigo_agent_auxiliary'
alias indigostop='killall indigo_server'
alias servod='sudo killall servod; sudo servod'
alias reboot='sudo reboot'
alias shutdown='sudo shutdown now'
alias update='sudo apt update && sudo apt full-upgrade && sudo apt dist-upgrade'
